[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
# - regular expression
regex = "1.3.9"

# - config dependencies
log.workspace = true
log4rs.workspace = true